server:
  port: 8080

app:
  allowedOrigins: ${ALLOWED_ORIGINS:*}

  lambda:
    functionUrl: https://sy6sba3jqufb3g3cbfr4bcfeau0pyjkb.lambda-url.ap-southeast-2.on.aws/

  # Email configuration
  email:
    # Your email address to receive contact form submissions
    to: ${CONTACT_EMAIL:juanmontoyas2003@gmail.com}
    
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:juanmontoyas2003@gmail.com}
    password: ${MAIL_PASSWORD:mnut iytt svwy wzjh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true